image: python:3.10-slim

stages:
  - test
  - report

variables:
  JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"
  PATH: "$JAVA_HOME/bin:$PATH"
  ALLURE_VERSION: "2.21.0"
  ALLURE_HOME: "$CI_PROJECT_DIR/allure"

before_script:
  - apt-get update && apt-get install -y openjdk-11-jdk wget unzip
  - wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
  - unzip -q allure-${ALLURE_VERSION}.zip -d $CI_PROJECT_DIR
  - mv $CI_PROJECT_DIR/allure-${ALLURE_VERSION} $ALLURE_HOME
  - export PATH=$ALLURE_HOME/bin:$PATH

test_job:
  stage: test
  script:
    - pytest --alluredir=allure-results
  artifacts:
    paths:
      - allure-results

report_job:
  stage: report
  dependencies:
    - test_job
  script:
    - $ALLURE_HOME/bin/allure generate allure-results -o allure-report --clean
  artifacts:
    paths:
      - allure-report
  when: always
