stages:
  - test
  - report

variables:
  JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"
  PATH: "$JAVA_HOME/bin:$PATH"

test_job:
  stage: test
  image: openjdk:11
  script:
    - java -version
    - ./run_tests.sh

allure_report:
  stage: report
  image: openjdk:11
  dependencies:
    - test_job
  script:
    - apt-get update && apt-get install -y wget unzip
    - wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
    - unzip allure-2.21.0.zip -d /opt/
    - export PATH=/opt/allure-2.21.0/bin:$PATH
    - allure --version
    - allure generate ./allure-results -o ./allure-report --clean
  artifacts:
    paths:
      - allure-report
    expire_in: 1 week
